//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PA.Codec
{
    public class JpegCodec : VideoCodec
    {
        public override byte[] Encode(object data)
        {
            return base.Encode(data);
        }

        public override object Decode(byte[] data)
        {
            return base.Decode(data);
        }
    }
}


