//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace PA.Codec
{
    public class VideoCodec : ICodec
    {
        public string CodecName
        {
            get
            {
                throw new NotImplementedException();
            }
        }

        public virtual byte[] Encode(object data)
        {
            return (byte[])data;
        }

        public virtual object Decode(byte[] data)
        {
            return data;
        }

    }
}


