//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using PA.Net.Clients;
using System.IO;

namespace PA.Crypto
{
    public class OpenChannel : SecureChannel
    {
        public OpenChannel(Stream stream, INetClient client, bool endPoint) : base(stream, client, endPoint)
        {

        }
    }
}


