//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PA.Net.Core
{
    public interface IDisposable
    {
        bool CanDispose { get; set; }

        void Dispose();

    }
}


