//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using PA.Codec;
using PA.Net.Clients;
using PA.Net.Core;

namespace PA.Distributer
{
    public interface IDistributer
    {
        INetClient Client { get; }
        ICodec Codec { get; set; }
        long UserID { get; }
        long RoomID { get; }
        bool Start();
        bool Stop();
        event ExceptionReportHandler ExceptionReported;
    }
}


