//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using PA.Codec;
using PA.Net.Clients;

namespace PA.Distributer
{
    public class WebcamDistributer : VideoDistributer
    {
        public WebcamDistributer(INetClient client, VideoCodecTypes videoType) : base(client, client.UserID, (client as LocalMediaClient).RoomID)
        {
            CreateCodec(videoType);
        }
    }
}


